### ISSUE TITLE
ScriptHandler::clearCache has newline before "true"

### ISSUE THREAD

**Issue by kbond** [symfony/symfony-standard#1026]
This started happening after I upgraded to 3.2. 

When running `composer install` the output is as follows:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
```

When running `bin/console cache:clear` the output is as follows:

```
 // Clearing the cache for the dev environment with debug true                                                          

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
```

Not a major issue but I can't figure out why this is happening...

**Comment by ogizanagi** [comment]
That's because the default width was arbitrary defined to 80 in the new [`Terminal` class](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Terminal.php#L34).

However, I'd expect https://github.com/symfony/symfony/pull/19724 will ensure we always get a terminal width even when a command is executed in a sub process, but it doesn't work right now with composer scripts because it doesn't use `symfony/console` 3.2 yet.

I'd expect a next composer release requiring 3.2 to fix it (can be tested by building a phar yourself), but it's unlikely to happen soon I guess :/

**Comment by kbond** [comment]
Thanks for the info @ogizanagi!

**Comment by ogizanagi** [comment]
However I still think there is an issue in the way the `comment` block is rendered by `SymfonyStyle` (it doesn't exceed 80 chars here).
I think it omits to take into account the `$message` decorated elements length. 😅

**Comment by jzawadzki** [comment]
@ogizanagi - you're right - this line ("Clearing the cache for the dev environment with debug true) is considered longer than 80 chars as `createBlock` wordwrap method does not look into decoration tags like `<info>` in that case 
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Style/SymfonyStyle.php#L399

**Comment by fabpot** [comment]
Closing as there is nothing to fix in Symfony SE.
