### ISSUE TITLE
Why is doctrine cache bundle required in composer.json

### ISSUE THREAD

**Issue by tommygnr** [symfony/symfony-standard#1050]
It's not configured at all and the [commit](https://github.com/symfony/symfony-standard/commit/d3ed0daada32630f852fb7f6636ce6b9413e4cdc) that introduced it doesn't provide a reason.

**Comment by stof** [comment]
I think the explicit requirement was added at that time to allow depending on the dev version of DoctrineBundle because DoctrineCacheBundle was not yet released at that time.
In the meantime, both DoctrineBundle 1.6 and DoctrineCacheBundle have been released. So the explicit requirement is not needed anymore (as we don't need to put ``@dev`` in it anymore)

**Comment by fabpot** [comment]
Indeed, @stof is right. See #1051
