### ISSUE TITLE
[DX] Why is SensioDistributionBundle a general requirement in `composer.json` but only added to the kernel in the development and test environments?

### ISSUE THREAD

**Issue by yhoiseth** [symfony/symfony-standard#1081]
SensioDistributionBundle is a general requirement in `composer.json`. See [line 19](https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L19).

At the same time, it's only added to the kernel if the environment is `dev` or `test`. See [line 24](https://github.com/symfony/symfony-standard/blob/3.3/app/AppKernel.php#L24).

Seeing that the bundle isn't added to the kernel in the production environment, one of my colleague moved the requirement to `require-dev` in `composer.json`.

This led to failed deployments because the `bootstrap.php.cache` file was missing. (SensioDistributionBundle handles the generation of said file.) The issue was fixed by moving the dependency back to `require`.

Why the discrepancy between `composer.json` and `app/AppKernel.php`?

**Comment by stof** [comment]
because SensioDistributionBundle is also the one providing the composer scripts used by the composer.json in all cases, not only in dev.

**Comment by Pierstoval** [comment]
It's because of [composer scripts](https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L34-L38) that are executed on each `composer install` or `composer update`, whatever the environment.

Moreover, if you are using `SYMFONY_ENV` environment var in your production env, the cache script will automatically clear production cache.
