### ISSUE TITLE
Improving the Symfony Standard Edition

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-standard#639]
Here are some things we **might** do to improve the current Symfony Standard Edition:

 * Improving the first step (installation mainly): see #622 
 * Managing bundles from configuration files (see #598 and #608 -- I'm mostly -1 on this one)
 * ~~Automate the removal of the Acme bundle or ask for its installation when creating a new project (#499 and many other issues talks about this one)~~ done in #643

**Comment by Pierstoval** [comment]
@vishalmelmatti I think it's possible, and I think that what you need is to use different `Environments`you may just need 1 `app` file for each application in the `web/` directory, and each `app` instanciates a different `Kernel` class.
 
Any `Kernel` class can register its own bundles, and with Symfony's [Environments](http://symfony.com/doc/current/cookbook/configuration/environments.html) you can specify any `parameters_{env}.yml`.
 
Let's get a clear example with a big application, where there are 3 environments : the front-end, the back-end and an API/Webservice manager.
Then we have 3 environments in the `web` directory:
`app_front.php`
`app_back.php`
`app_api.php`
 
Each one instanciates a different `Kernel` class, which you can copy/paste from the original `Kernel` in your `app` directory:
app_front.php => $kernel = new AppFrontKernel('front');
app_back.php => $kernel = new AppBackKernel('back');
app_api.php => $kernel = new AppApiKernel('api');
 
Each kernel will instanciate its own bundles, but still use the same logic as Symfony uses (autoloading, security, etc.) for you to have the same configuration parameters for many "reusable" cross-bundle features.
And with the namespacing, you can use the great powers of the autoloader, by setting your own bundle architecture in the `src` directory like this for example:
`src/CompanyName/Front/AngularBundle`
`src/CompanyName/Back/AdminBundle`
`src/CompanyName/Api/WebserviceBundle`
`src/CompanyName/Common/DatabaseBundle`
Of course, all your bundles can be stored in something specific (front, back, api) or in the common namespace, especially for your `Entity` or `Document` classes which are probable reused all over your app.

And then, everything is stored in a single same repository :smile: 

And for your web server, if you use Apache, you can get rid of the `.htaccess` file in the `web/` directory, and write all instructions directly in your Apache configuration, virtual hosts, etc, by changing the `DirectoryIndex app.php` instruction into the one you need for your virtual host or domain name configuration.

I hope I understood well your needs. :)

**Comment by Wirone** [comment]
@Pierstoval I think it's not truth what you said:

> And for your web server, if you use Apache, you can get rid of the `.htaccess` file in the `web/` directory, and write all instructions directly in your Apache configuration, virtual hosts, etc, by changing the `DirectoryIndex app.php` instruction into the one you need for your virtual host or domain name configuration.

`DirectoryIndex` directive only informs Apache which files it should look for when file's name is not present in URL. In case when you have 3 `VirtualHost`s with 3 environment-entry points in common `DocumentRoot`, you can't be sure that someone won't use it in a way you did not want to.

For example - you have routing based on subdomain `api.example.com`, `VirtualHost` with `DirectoryIndex app_api.php` where `AppApiKernel` is used. You can't forbid user to manually input `api.example.com/app_front.php` and if user will do so, it won't work since it's completely OK for Apache but `app_front.php` won't register API bundle, routing will not be included and so on..

I think it could be handled with more complex structure or `RewriteCondition` - checking domain and script file, redirecting when don't match.
