### ISSUE TITLE
what's this? de_

### ISSUE THREAD

**Issue by tangtang1251** [symfony/symfony-standard#798]
version : 2.7
it's error when i run php app/console cache:clear . 
[2015-04-14 11:46:21] php.WARNING: unlink(/usr/local/var/www/symfony-standard-2.7/app/cache/`de_`/annotations/552c8d8d980d34.40127459qhMRLB): No such file or directory {"type":2,"file":"/usr/local/var/www/symfony-standard-2.7/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php","line":214,"level":4352}

i guess de_ is dev environment?

**Comment by cordoval** [comment]
are you using vagrant? if so maybe it is related to your mounted folder

**Comment by tangtang1251** [comment]
No, This website is running on my local(127.0.0.1:8000).
directory app/cache/de_/annotations/ is empty;

**Comment by haus23** [comment]
Can confirm. And got a similar error on php app/console cache:clear --env=test .
Here the missing folder is tes_

**Comment by Pierstoval** [comment]
I've already seen that, and in fact I've never investigated on this issue, because I think it's coming from the cache system. When you use `app/console cache:clear` directly, Symfony warms up the cache after cleaning it, so maybe it stores other cache components inside another directory before warming up the cache with the "cached cache" contents.
 
Can one of the core developers confirm such behavior?

**Comment by tangtang1251** [comment]
@haus23 
temp directory name rule is https://github.com/symfony/FrameworkBundle/blob/master/Command/CacheClearCommand.php#L78

copy real to temp, delete temp cache file, delete real, rename tempname to realname.
i think, error since https://github.com/symfony/Routing/blob/master/Router.php#L373
(chinglish > _ <)

**Comment by weaverryan** [comment]
Is this only affecting people on 2.7? Or does it affect other versions?

`de_` (or `tes_`) *is* the name of the new directory Symfony is "warming up" as @Pierstoval described. irrc, `dev` is then moved to `dev_old` and `de_` is moved to `dev`: https://github.com/symfony/FrameworkBundle/blob/master/Command/CacheClearCommand.php#L92. So, I'm not clear why something would be removed from `de_` (the directory that's being warmed up).

**Comment by Pierstoval** [comment]
In one of my apps, I'm using SF2.7 and I sometimes have this kind of warning message, but it does not stop the app from executing :confused:

**Comment by jakzal** [comment]
re https://github.com/symfony/symfony/issues/14353

**Comment by Soullivaneuh** [comment]
@weaverryan I think it's only for 2.7.

Personally, I have this error since upgrading to `2.7.0-BETA1`.

I was before on `2.7.x-dev` (2.7.x-dev 350f30b0e1651371a5a31c61c5d13c972b9d5c24) and didn't get this kind of error.

**Comment by xelaris** [comment]
I think the fundamental issue was fixed in https://github.com/doctrine/annotations/commit/8e87c6391285085e5c2889a86f201a48ae2dcab1 and will be included in the next release of `doctrine/annotations`.
The question IMO is, why the php warning is displayed, while the `unlink` statement is silenced.

Calling `app/console clear:cache --no-debug` does not provide these warnings. So I think they are collected by a custom error handler and provided explicitly.
