### ISSUE TITLE
Add twig file name and paths as html comment in dev environment.

### ISSUE THREAD

**Issue by m-amr** [symfony/symfony-standard#870]
When twig render a template which include other templates add these template paths as html comments in Dev environment will help developer to find the template using browser inspect element.
and some information about the data passed to these template

for example
```

   <!-- @bundlename:sidebar.twig.html-->
   <div id ="sidebar"> </div>
   <!-- @bundlename:mainView.twig.html-->
   <div id ="main_view"></div>

```

**Comment by stof** [comment]
2 things here:

- this has nothing to do in the symfony-standard repository, as symfony-standard cannot do anything for this
- this has already been discussed in the Twig issue tracker in the past, and rejected, because it would be far too easy to have cases where the injected comment breaks everything. See https://github.com/twigphp/Twig/pull/1608

**Comment by m-amr** [comment]
@stof  Thanks ... will close this Issue.
