### ISSUE TITLE
Sf3 directory structure cannot be triggered with composer

### ISSUE THREAD

**Issue by ZeeCoder** [symfony/symfony-standard#873]
I'm quite fond of the new dir structure, but I can't trigger it with >2.7.4 versions.
The following didn't work for 2.7.5 for me, but worked with 2.7.4:
`SENSIOLABS_ENABLE_NEW_DIRECTORY_STRUCTURE=true composer create-project symfony/framework-standard-edition <etc...>`

**Comment by Pierstoval** [comment]
IIRC it was removed from the 2.x branch until Symfony3 will release

**Comment by ZeeCoder** [comment]
Thanks for the fast reply @Pierstoval :)

Well I see, it's a shame. O.o

So is the usage even discouraged now?
If I use the sf3 structure, and update symfony later, could it cause issues?

**Comment by jvasseur** [comment]
You can create a new project with symfony 3 (that will get you the new directory structure) and then switch your symfony version to the one you want to use.

**Comment by Pierstoval** [comment]
No because the structure can be defined according to the `composer.json` extra fields, but actually, if I remember the discussions, it was removed mostly because it wasn't 100% settled at that time, but now that the SF3 structure is decided and approved it's OK for the team, and the migration has started (you can see #850 #857 #859 and #862 for example)
 
But you can still use the SF3 structure in your app.
 
The structure is only relied to the standard edition, not Symfony itself ;)

**Comment by ZeeCoder** [comment]
I see, thanks for the detailed answers!

**Comment by stof** [comment]
> The structure is only relied to the standard edition, not Symfony itself

That's not really true. To be able to use the Symfony 3 structure in a Symfony 2 project, you need to customize the cache and logs dirs in your own kernel (as described in http://symfony.com/doc/current/cookbook/configuration/override_dir_structure.html), as the kernel in Symfony 2 won't use the new structure.
The fact that SensioLabsDistributionBundle was using a hack to try to avoid this need previously was causing many issues for people enabling the 3.0 structure

**Comment by Pierstoval** [comment]
Thanks @stof for the details, it helps understand why it was removed from the 2.x branches :)

**Comment by ZeeCoder** [comment]
Thanks for the additional info @stof , I'll customize the kernel accordingly. :+1:
