### ISSUE TITLE
composer.json's scripts are inconsistent with dependencies

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony-standard#913]
`composer install --no-dev` fails with

    An error occurred when executing the "'cache:clear --no-warmup'" command:
    PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in ./app/AppKernel.php on line 25

(that happens with at least v2.8, not sure about v3)

**Comment by Pierstoval** [comment]
The problem is simply caused by the fact that the `ScriptHandler::clearCache` does not specify the environment used, so using `--no-dev` will still use the default environment in the console, which is `dev` by default.
 
I don't know if the script handler should take environments in account :confused:

**Comment by bocharsky-bw** [comment]
I think `export SYMFONY_ENV=prod` could help you without specifing --env=prod each time in console.

**Comment by zerkms** [comment]
@bocharsky-bw It's not about invoking console commands manually. The problem is that the current `project.json` is simply incorrect.

**Comment by Pierstoval** [comment]
@zerkms This problem is recurrent, we often have it while deploying with Capifony for example, or when automating the deploy with git or something else, because the `composer install --no-dev` does not install the `sensio/generator-bundle` package, which is required only in `dev`.
 
So then after that, the `post-install-cmd` scripts are called, and the `clearCache` script handler is executed. This handler only executes `app/console cache:clear`, so it does not specify any environment info. The default one is `dev`. Which requires `SensioDistributionBundle`. And as it is not installed because of the `--no-dev` option in `composer install`, an error is thrown.
 
It's not about the `composer.json` file, it's more about the `ScriptHandler::clearCache` command.

**Comment by zerkms** [comment]
@Pierstoval I clearly understand the roots of the problem: it's about `composer.json`'s scripts, that invokes something that is not installed.

So it either should not invoke a bundle that it does not install or should install it - easy-peasy :-)

**Comment by bocharsky-bw** [comment]
@zerkms I guess it's obvious when you do `composer install --no-dev` you should do `export SYMFONY_ENV=prod` first.

**Comment by zerkms** [comment]
@bocharsky-bw yep, it would help indeed, but it's not expected that `composer install` command fails unless you set some environment variables first.

**Comment by Pierstoval** [comment]
The problem is that Composer and Symfony are different from each other. There are lots of connections between them because of the scripts, but actually, I think a proper documentation in the installation process is better than implementing this.

> So it either should not invoke a bundle that it does not install or should install it - easy-peasy :-)
 
Installing it is wrong: Symfony throws an error because a bundle is not installed, but if it's not installed it is *on purpose*, thanks to the `--no-dev` option.
And for the "no invoke" part, it's also impossible to not invoke it because the `app/console` command has default `dev` environment, and not `prod`.
 
Using the env var is the best solution, as proposed by @bocharsky-bw.

The *correct* install command for a Symfony application would be the following:

```bash
# Dev
$ composer install

# No dev
$ SYMFONY_ENV=prod composer install --no-dev 
```

If the environment is different and is something like `int`, `staging` or `preprod` and it does not need `require-dev` dependencies, it's application-related, and this logic *must not* (IMO) reside in the `ScriptHandler::clearCache` script.

**Comment by zerkms** [comment]
So, closing this then. Thanks.
