### ISSUE TITLE
Polyfill in Standard Edition

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-standard#970]
I cannot find any information about ``Symfony polyfill`` in the Standard Edition. Is it already included by any of the dependencies? Or must I additionally add it to ``composer.json``?

I think the Standard Edition should contain these polyfill features by default because it supports ``php >= 5.5.9`` (see ``composer.json``):

symfony/polyfill-php56 for using the new functions introduced by PHP 5.6
symfony/polyfill-php70 for using the new functions introduced by PHP 7.0

**Comment by WouterJ** [comment]
Nothing in the Symfony Standard Edition depends on functionalities that have polyfills in those packages, so it makes no sense to depend on it.

Symfony core framework depends on these packages whenever it needs them. So in the end, when running `composer update/install` in the SE, you probably get some polyfill packages because they are used by the core code.
