### ISSUE TITLE
[UX] frameworkbundle console should not run in debug on prod installs

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-standard#975]
This is a usability problem.

If you try to run a `php bin/console` from any production install symfony distribution or the symfony frameworkbundle, you will get a `Fatal error: Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /yourproject/app/AppKernel.php`.

That is because by default the console runs in debug mode, so you have to `--env=prod` on every single command you write. I shouldn't have to do this if I didn't even install the dev dependencies from composer (where the generator bundle is by default).

At the very least it could intercept this particular error (which will occur with a default composer.json from the distribution) and tell me that I need to run my command with `--env=prod`, then give me the error as normal in case that isn't the case.

But best case would be it should works without `--env`, perhaps warning me that dev commands are not available because they were not installed.

~ imo any error that is not easily understood should be treated as a bug

**Comment by Pierstoval** [comment]
Use the `SYMFONY_ENV` environment var.

You can do it for example in `~/.bashrc` (or `~/.bash_profile` depending on your OS) and add 
`export SYMFONY_ENV='prod'` and you're set, default env is `prod` on every command, unless you specify `--env=dev`.

**Comment by ofbeaton** [comment]
I agree that solves having to specify `--env` on every command, though having to specify it when I didn't even install the dev dependencies is less than ideal.

It also does not address the usability and experience of the error message. That could be drastically improved.

**Comment by Pierstoval** [comment]
Knowing that dev dependencies are installed is an "issue" (if it really is) that should find a solution in composer itself (via autoload, etc.). The only way, actually, to check for dev dependencies is to check that some class specific to dev dependencies exist, but doing this in the standard edition seems wrong to me because anyone could remove this "dev" class from its dependencies...

**Comment by ofbeaton** [comment]
It wouldn't be foolproof, but if the console runs in `dev` it could catch the AppKernel and if it blows up with a `Class not found` error for `SensioGeneratorBundle`, print out `You are running in this command in dev mode, if you meant to run it in prod please specify --env=prod or set SYMFONY_ENV`. Then append the actual exception.

In fact, I would argue that you should print out such a message if running in dev and any `Class not found` error happens in the AppKernel. It would be a common mistake when deploying to prod and would help people troubleshoot this.

The point isn't to catch really obscure edge cases but to catch the main cases that the symfony distribution ships with.

**Comment by Pierstoval** [comment]
I totally understand what you need and it's relevant. 
 
But showing this message on any `Class not found` is not a good idea, because these errors can come from other mistakes (untested code, which is very common for non-fully-tested apps in many companies).
 
However, looking for the `SensioGeneratorBundle` seems a good start, but I don't know if the Symfony team would find this important enough to be implemented in the standard edition :confused:

**Comment by ofbeaton** [comment]
It is tricky to do it upstream in say an autoloader (like Composer's) because they have no guarantee that they are the only autoloader (see discussions there). Since `spl-autoload-register` specifies that your autoloader should return `false` when it cannot find a class, instead of throw some specified ClassNotFound exception, it is impossible for them to touch the eventual exception.

That means that it is really the application (the symfony console in this case), which is the only one who can catch and re-throw the exception to insert more information.

**Comment by Pierstoval** [comment]
If Composer does not provide any solution for us to detect that `require-dev` dependencies were installed, there are three solutions to your issue:

1. Open an issue in [composer/composer](https://github.com/composer/composer) and ask/work for an implementation of a solution to add some kind of "metadata" to Composer's autoloader where we could know whether the `require-dev` dependencies were installed.

  **Pros**: a really cool solution, maybe the best.
  **Cons**: To add it in the standard edition, we'll have to wait a few months, because not everyone update its Composer installation even with the warnings.
2. Use the environment var.

  **Pros**: Very clean, and totally corresponds to what should be done in a real prod environment.
  **Cons**: You have to set it up.
3. Search for `SensioGeneratorBundle`.

  **Pros**: Easy to set up and can be done in the standard edition.
  **Cons**: Anyone removing this bundle or not using the standard edition wouldn't be able to use it.

**Comment by fabpot** [comment]
I'm closing ,this as this is not something we can easily fix here (and solutions have been given). Symfony Flex (the replacement for this edition) does not suffer from this issue.
